apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordermanagement-1-deployment
  labels:
   app: ordermanagement-1
spec:
  replicas: 1
  selector:
   matchLabels:
    app: ordermanagement-1
  template:
    metadata:
      labels:
        app: ordermanagement-1
    spec:
      containers:
        - name: ordermanagement-1
          image: prabhupalanivel/ordermanagement-1
          ports:
            - containerPort: 8866
